### ISSUE TITLE
Use a static analyzer

### ISSUE THREAD

**Issue by jola5** [jola5/gtv#16]
There's [shellcheck](https://github.com/koalaman/shellcheck), a static analyzer for shell scripts. It looks awesome and [travis integration seems so easy](https://github.com/koalaman/shellcheck#travis-ci-setup): 

```yaml
language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
```

Addition: 
Fix issues stated by `shellcheck`.
